# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/


language: "en"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "EmbeddingIntentClassifier"
  random_seed: 1


policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 15
  - name: AugmentedMemoizationPolicy
    max_history: 15
  - name: FormPolicy
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.70
    ambiguity_threshold: 0.1
    core_threshold: 0.50
    # fallback_action_name: "out_of_scope"
